In [13]:
#NumPy

#create 1d,2d,and 3d array

import numpy as np

a=np.array([1,4,6,7])
b=np.array([[1,2,3],[4,7,2]])
c=np.array([[[3,6,8],[2,8,9]],[[6,7,4],[4,3,1]]])

print(a)
print(b)
#getting the dimensions
print(c.ndim)
#accessing a index
print(c[0,1,2])
#adding
print(c[0,0,0] + c[1,1,1])


[1 4 6 7]
[[1 2 3]
 [4 7 2]]
3
9
6


In [28]:
#slicing
import numpy as np

a=np.array([2,6,4,7,9,1,0])

print(a[1:4])
print(a[:6])
print(a[:])
print(a[3:])

print(a[-6 : -2])
print(a[1::3])

[6 4 7]
[2 6 4 7 9 1]
[2 6 4 7 9 1 0]
[7 9 1 0]
[6 4 7 9]
[6 9]


In [31]:
#slicing of a 2D and 3D array

import numpy as np

a=np.array([[2,5,6,8],[4,3,8,1]])
print(a[1,:3])

b=np.array([[[1,3,4,7],[8,3,2,8]],[[3,9,7,4],[4,2,1,5]]])
print(b[0,1,1:3])

[4 3 8]
[3 2]


In [33]:
import numpy as np

a=np.array([[3,5,6,7,8],[3,8,9,1,2],[5,6,4,3,1]])
print(a[:,1:4])

[[5 6 7]
 [8 9 1]
 [6 4 3]]
